return {
    name = 'Tango! Color Palette',
    curator = 'Linuxdirk',
    description = 'Color palette from the Free Desktop Project',
    pixels = {
        { color = '#fce94f', name='Butter Light' },
        { color = '#edd400', name='Butter Normal' },
        { color = '#c4a000', name='Butter Dark' },
        's',
        { color = '#eeeeec', name='Aluminium Light' },
        { color = '#d3d7cf', name='Aluminium Normal' },
        { color = '#babdb6', name='Aluminium Dark' },
        'n',
        { color = '#fcaf3e', name='Orange Light' },
        { color = '#f57900', name='Orange Normal' },
        { color = '#ce5c00', name='Orange Dark' },
        's',
        { color = '#888a85', name='Slate Light' },
        { color = '#555753', name='Slate Normal' },
        { color = '#2e3436', name='Slate Dark' },
        'n',
        { color = '#e9b96e', name='Chocolate Light' },
        { color = '#c17d11', name='Chocolate Normal' },
        { color = '#8f5902', name='Chocolate Dark' },
        'n',
        { color = '#8ae232', name='Chameleon Light' },
        { color = '#73d216', name='Chameleon Normal' },
        { color = '#4e9a06', name='Chameleon Dark' },
        'n',
        { color = '#729fcf', name='Sky Blue Light' },
        { color = '#3465a4', name='Sky Blue Normal' },
        { color = '#204a87', name='Sky Blue Dark' },
        'n',
        { color = '#ad7fa8', name='Plum Light' },
        { color = '#75507b', name='Plum Normal' },
        { color = '#5c3566', name='Plum Dark' },
        'n',
        { color = '#ef2920', name='Scarlet Red Light' },
        { color = '#cc0000', name='Scarlet Red Normal' },
        { color = '#a40000', name='Scarlet Red Dark' },
    }
}
